# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
encoding: utf-8
title: もやもやプログラミング2
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  プログラミング・ソフトウェア開発に関する技術ブログです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mmktomato.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: high_beamer
#twitter:
#  username: high_beamer
github_username:  mmktomato

# Build settings
markdown: kramdown
theme: minima
#remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

timezone: Asia/Tokyo
future: true
lang: ja
author: mmktomato
google_analytics: UA-112740987-1

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
